In [2]:
import numpy as np
import pandas as pd

# Load the data
data =pd.read_csv("ml_dataset.csv")

data = data.drop(columns=['gender','work_type','ever_married','Residence_type','smoking_status']) 

data.dropna(axis=0, inplace=True)

# Preprocess the data
X = data.drop(columns=['stroke']).to_numpy() 
y = data['stroke'].to_numpy()

import numpy as np
from sklearn import svm
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# Create an instance of the SVM classifier
clf = svm.SVC()

# Train the SVM model with the training data
clf.fit(X_train, y_train)

# Get the support vectors
support_vectors = clf.support_vectors_

# Number of support vectors for each class
n_support_vectors = clf.n_support_

print("Support Vectors:")
print(support_vectors)
print("Number of support vectors for each class:", n_support_vectors)


Support Vectors:
[[4.1480e+03 8.1000e+01 0.0000e+00 0.0000e+00 7.1180e+01 2.3900e+01]
 [6.7603e+04 7.0000e+01 0.0000e+00 0.0000e+00 2.2368e+02 3.4300e+01]
 [6.0258e+04 8.0000e+01 0.0000e+00 1.0000e+00 9.8390e+01 2.2200e+01]
 ...
 [4.6510e+03 7.8000e+01 0.0000e+00 0.0000e+00 7.8030e+01 2.3900e+01]
 [3.1154e+04 3.9000e+01 0.0000e+00 0.0000e+00 9.7760e+01 2.9600e+01]
 [2.4669e+04 7.7000e+01 0.0000e+00 1.0000e+00 2.3156e+02 3.6900e+01]]
Number of support vectors for each class: [212 156]


In [3]:
accuracy = clf.score(X_test, y_test)
print("Accuracy:", accuracy)

Accuracy: 0.9460285132382892


In [4]:
y_pred = clf.predict(X_test)

In [5]:
clf_linear = svm.SVC(kernel='linear')
clf_linear.fit(X_train, y_train)
accuracy_linear = clf_linear.score(X_test, y_test)
print("Accuracy (Linear Kernel):", accuracy_linear)

Accuracy (Linear Kernel): 0.945010183299389


In [6]:
clf_poly = svm.SVC(kernel='poly')
clf_poly.fit(X_train, y_train)
accuracy_poly = clf_poly.score(X_test, y_test)
print("Accuracy (Polynomial Kernel):", accuracy_poly)


Accuracy (Polynomial Kernel): 0.9460285132382892


In [7]:
clf_rbf = svm.SVC(kernel='rbf')
clf_rbf.fit(X_train, y_train)
accuracy_rbf = clf_rbf.score(X_test, y_test)
print("Accuracy (RBF Kernel):", accuracy_rbf)


Accuracy (RBF Kernel): 0.9460285132382892
